// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {request} from '../models';
import {common} from '../models';

export function GetAfrogList(arg1:request.PocSearchInfo):Promise<common.H>;

export function GetOrganization(arg1:request.PocSearchInfo):Promise<common.H>;

export function Greet(arg1:string):Promise<string>;

export function InfoCollectionStart():Promise<string>;

export function ReadAfrogPoc(arg1:string):Promise<common.H>;
