// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAfrogList(arg1) {
  return window['go']['main']['App']['GetAfrogList'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InfoCollectionStart() {
  return window['go']['main']['App']['InfoCollectionStart']();
}

export function ReadAfrogPoc(arg1) {
  return window['go']['main']['App']['ReadAfrogPoc'](arg1);
}
